FROM node:16

# Create app directory
WORKDIR /usr/src/app

RUN  apt-get -y update && apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

COPY package*.json ./
RUN yarn install

COPY . .
EXPOSE 6969

CMD ["yarn", "run", "dev"]